[package]
name = "ext4tool"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
ext4 = { path = ".." }
anyhow = "1"
bootsector = "0.2"
cast = "0.2"
clap = "2"
hexdump = "0.1"
